apiVersion: v1
kind: Secret
metadata:
  name: fcg-users-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=users-sqlserver,1433;Database=FCGUsersDb;User Id=sa;Password=senha123@#4l;TrustServerCertificate=True;Encrypt=False"

  SqlServer__SaPassword: "senha123@#4l"

  Jwt__SecretKey: "Q8m5L2b0V0xSgFJq9nR4pY7eTcW1uNzKk3XhM8aPvL2YzR5fGb1nC9wE6sDtQ7uH"

  Notifications__FunctionKey: ""
