apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-sqlserver
  namespace: fcg
  labels:
    app: users-sqlserver
spec:
  replicas: 1

  selector:
    matchLabels:
      app: users-sqlserver

  template:
    metadata:
      labels:
        app: users-sqlserver

    spec:
      containers:
        - name: users-sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest

          ports:
            - name: sql
              containerPort: 1433

          env:
            - name: ACCEPT_EULA
              value: "Y"

            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fcg-users-secret
                  key: SqlServer__SaPassword

          volumeMounts:
            - name: users-sqlserver-storage
              mountPath: /var/opt/mssql

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "1"
              memory: "2Gi"

      volumes:
        - name: users-sqlserver-storage
          persistentVolumeClaim:
            claimName: users-sqlserver-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: users-sqlserver
  namespace: fcg
spec:
  type: ClusterIP

  selector:
    app: users-sqlserver

  ports:
    - name: sql
      protocol: TCP
      port: 1433
      targetPort: 1433

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-sqlserver-pvc
  namespace: fcg
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi